### PR TITLE
Added a hook for custom pieces

### PR DESCRIPTION
**Pull request by LuaTenshi**
Added a hook to allow custom pieces within ULib.getUsers. Lines: 219 - 223

Here is a quick example...

hook.Add("ulx_custompiece", "__j", function(ply, p) 
	if p:sub( 1, 1 ) == "&" then
		local uSel = ply._ulxSelection
		if uSel and type(uSel) == "table" and #uSel >= 1 then
			local tab = {}
			for _,v in next, ply._ulxSelection do
				if IsValid(v) and v:IsPlayer() then
					table.insert(tab, v)
				end
			end
			return tab
		else
			return nil
		end
	end
end)

### CODE REVIEW

**Comment by iSnipeu** [comment]
This seems to have been forgotten and looks quite useful.

**Comment by LuaTenshi** [comment]
Yep, sadly. Maybe because my example code is a bit messy.

**Comment by SticklyMan** [comment]
Megiddo has been interested in this- I recall him saying he wanted to make a few slight changes to it before implementing it. We just haven't had time quite yet :-\

**Comment by Nayruden** [comment]
Implemented as above.

**Pull request closed without merging**
