### PR TITLE
fix hook system

### PR DESCRIPTION
**Pull request by LennyPenny**
this is the most disgusting and slow code ever to be put in a gmod addon (after rocketmanias 1k+ fonts)
if you were serious about "development" you wouldn't have introduced this

-20 to 20?? who the fuck made that up

### CODE REVIEW

**Comment by LennyPenny** [comment]
cba annoyed to fix all the hook.adds that pass a 4th parameter right now

just let ulx shit itself

**Comment by meepdarknessmeep** [comment]
+support

**Comment by Lonke** [comment]
Looks great! Make this happen ULX Team.

**Comment by Nayruden** [comment]
Do you really expect us to make a change based only on your emotional,
clearly ignorant argument? Calm down, do your homework, and give us at
least a single good reason to make this change.

**Comment by LennyPenny** [comment]
performance

**Comment by Nayruden** [comment]
That further shows your ignorance. ULib's hook implementation is more
performant than Garry's.

On Tue, Jan 6, 2015 at 11:44 AM, Lennart Bernhardt <notifications@github.com

**Comment by cartman300** [comment]
It IS slow as fuck.

**Comment by gurustephen** [comment]
Have you never used Linux before? Learn about niceness and process priorities here: http://www.ibm.com/developerworks/library/l-lpic1-v3-103-6/

"The NI column in Listing 1 above, shows the scheduling priority or niceness of each process. Niceness generally ranges from -20 to 19, with -20 being the most favorable or highest priority for scheduling and 19 being the least favorable or lowest priority."

**Comment by LennyPenny** [comment]
it doesnt even follow that vague guideline

**Comment by LennyPenny** [comment]
>That further shows your ignorance. ULib's hook implementation is more
performant than Garry's.

lmao

**Comment by SticklyMan** [comment]
Have you never used Linux before? Here: http://www.ibm.com/developerworks/library/l-lpic1-v3-103-6/

"The NI column in Listing 1 above, shows the scheduling priority or niceness of each process. Niceness generally ranges from -20 to 19, with -20 being the most favorable or highest priority for scheduling and 19 being the least favorable or lowest priority."

**Comment by Nayruden** [comment]
Troll somewhere else, Lennart. I've given you clear help and instructions.

On Tue, Jan 6, 2015 at 11:48 AM, Lennart Bernhardt <notifications@github.com

**Comment by LennyPenny** [comment]
for k=1, #HookTable do		
local v = HookTable[ k ]

ulysses this just makes me cry ok

**Comment by SticklyMan** [comment]
Closing this pull request. Removing the hook library would break ULX and require some work to re-implement.

If you feel that this is causing a big of a problem as you claim, prove it by profiling it yourself by profiling some code, and sending us both the code and results.

**Comment by LennyPenny** [comment]
yea someone is working on that I think, maybe

**Comment by wiox** [comment]
this is a stupid pr

**Comment by HandsomeMatt** [comment]
+support

**Comment by darkjacky** [comment]
Look I have no idea why you would want this removed. It seems very useful. I use it.

The only problem I have with it is that its not run from -20 to 20. it runs like: -1 -10 -11 -12 -13 -14 -15 -16 -17 -18-19 -2 -20 -3 -4 -5 -6 -7 -8 -9 0 1 10 11 12 13 14 15 16 17 18 19 2 20 3 4 5 6 7 8 9.

I don't think this is intended (I am certain) but it is not a huge problem either.

tell me if you want me to make a issue report. I will add the code I used to test this.

**Comment by SticklyMan** [comment]
@darkjacky Sure- If you can replicate it and have code, we'd love to take a look at it.

**Comment by darkjacky** [comment]
timer.Simple( 5, function()
	for i=-20, 20 do
		hook.Add("customhook", "customhook"..i,function() 
			print(i)
		end)
	end
	hook.Call( "customhook" )
end )

this is the code I used. but you can change the hook to anything and it will still run like that.

**Comment by SticklyMan** [comment]
darkjacky: It looks like you're forgetting to set the priority at the end of the hook.Add- Could you test this and see if the same thing happens?

timer.Simple( 5, function()
for i=-20, 20 do
hook.Add("customhook", "customhook"..i,function() 
print(i)
**end, i)**
end
hook.Call( "customhook" )
end )

**Comment by darkjacky** [comment]
I see the problem yes. and doing that fixes it yes. however, this piece of code will run like what i said -1 ending with 9

	for i=-20, 20 do
		hook.Add("Think", "customhook"..i ,function() 
			print(i)
		end, i)
	end

and this piece of code will run from -20 to 20

	timer.Simple(2, function()
	for i=-20, 20 do
		hook.Add("Think", "customhook"..i ,function() 
			print(i)
		end, i)
	end
	end )

So I still think something is not right.

**Comment by Divran** [comment]
@LennyPenny I just looked at the code, and while it can be optimized a tiny bit, that won't significantly affect performance at all, really. Where it matters most, in hook.Call, it is already faster than garry's since `for i=1,#tbl do` (which this code uses) is faster than `for k,v in pairs( tbl ) do` (which garry's uses)

Furthermore, Gmod's hooks should've had a priority system to begin with. It gives developers much more control over what happens.

Get your facts straight before insulting other people's work.

**Comment by Nayruden** [comment]
jacky, are you sticking that in an autorun? If so, it's executing before
ULib loads.

**Comment by SticklyMan** [comment]
@darkjacky: Technically, ULib would be a dependency of whatever hook required priorities, and should be initialized via the <whichever addon>\ulib\modules\ folder.

Although, I agree with @Divran - Some developers find the hook priority feature useful, and we've been wanting to get it cleaned up, optimized, and potentially included with GMod by default.

**Comment by darkjacky** [comment]
yes I am. This clears everything. So there are no problems. it functions perfectly as it should.
And I agree with this:
"Furthermore, Gmod's hooks should've had a priority system to begin with. It gives developers much more control over what happens." from @Divran
Should I be looking at the speed of the default vs the Ulib? SysTime() should do for that.

**Comment by SticklyMan** [comment]
Thanks for investigating that for us, @darkjacky- we always love having a second pair of eyes on things!

Any profiling you guys would like to do is great.

**Comment by LennyPenny** [comment]
@Divran just stop

anyway look at this https://github.com/Nayruden/Ulysses/pull/386

**Comment by knoxed** [comment]
I support this, even tho I don't have a clue what you guys are talking about.

**Comment by darkjacky** [comment]
if Garry is indeed using for k,v in pairs( tbl ) do
he is doing it wrong. 
for k,v uses 0.91510819199993 seconds to load 1000000 functions.
for i= uses 0.014264445000663 seconds to load 1000000 functions.

now i'll admit that 1000000 functions is an extreme amount.
and also that this was tested before. I will now go and look into the real functions.

if i am doing something wrong here please tell me.
---------------------------------------------------------------------------------------------------------------

first test = hook.Add

function used:

if SERVER then
	timer.Simple(5, function()
		local time = SysTime()
		for i=1,1000 do
			hook.Add("Think",string.char(math.random(65,90), math.random(65,90), math.random(65,90), math.random(65,90), math.random(65,90), math.random(65,90), math.random(65,90), math.random(65,90), math.random(65,90)), function()
			
			end )
		end
		print(SysTime() - time)
	end )
end

test results.
ulx = 0.550394955
default = 0.0017712939999939

Default scores better.

second test hook.Run

function used:

if SERVER then
	hook.Add("stupidhook","stupidhook", function()
		return false
	end)
	hook.Add("stupidhook","stupidhook", function()
		return false
	end)
	timer.Simple(5, function()
		local time = SysTime()
			for i =1, 100000 do
				hook.Run("stupidhook", "asd")
			end
		print(SysTime() - time)
	end )
end
test results.
default = 0.027754372999993
ulx = 0.038739671000002

default wins again.

1 more test again with hook.Run

function used:

if SERVER then
	for i =1, 100 do
		hook.Add("stupidhook",string.char(math.random(65,90), math.random(65,90), math.random(65,90), math.random(65,90), math.random(65,90), math.random(65,90), math.random(65,90), math.random(65,90), math.random(65,90)), function()
			return false
		end)
	end


	timer.Simple(5, function()
		local time = SysTime()
			for i =1, 100000 do
				hook.Run("stupidhook", "asd")
			end
		print(SysTime() - time)
	end )
end


default = 0.026116219999999
ulx = 0.054414179999981

well default wins.

so I have no idea why the default wins but is seems to.

**Comment by LennyPenny** [comment]
Yea let's post arbitrary speed tests
pairs owns you by far in this one

img

As you can see by the e^-006 it's like a lot faster

but this kind of stuff doesn't really mean anything

**Comment by Divran** [comment]
@LennyPenny CurTime is not accurate, use SysTime

**Comment by meepdarknessmeep** [comment]
my version: 0.041655872986667
ulx version: 0.092568515407038
default: 0.14928162329215

**Comment by meepdarknessmeep** [comment]
code used:
hook.Add("stupidhook", "ayy", function()
end);
hook.Add("stupidhook", "ayy2", function()
end, 1);

timer.Simple(5, function()
    local time = SysTime()
        for i =1, 100000 do
            hook.Run("stupidhook", "asd")
        end
    print(SysTime() - time)
end )

**Comment by LennyPenny** [comment]
@Divran it's accurate enough for shitty tests like this
img

**Comment by LennyPenny** [comment]
@Nayruden can someone delete this it's really become a circle jerk

**Comment by wiox** [comment]
good job, losers

**Comment by Divran** [comment]
@LennyPenny you're the one who said performance was the main reason this hook library should be deleted, and then you say performance tests are "shitty".

**Comment by Nayruden** [comment]
Meep, though I only glanced at your pr, it seemed to be missing the
read-only hook enforcement at either end of the hook spectrum (read the
comments in hook.lua for more).

**Comment by LennyPenny** [comment]
@Divran 
yeah I never said for i loop vs pairs loop was the problem

**Comment by Nayruden** [comment]
@LennyPenny, I get the idea you do not like people disagreeing with you. In
any case, I'm interested in the discussion because as mentioned by Stickly,
we are looking to submit something similar to our hook library for
inclusion into the default gmod code base.

**Comment by Divran** [comment]
@LennyPenny well as I said earlier, the code in the hook.Call functions of this hook module and garry's are pretty much identical, so then what is the problem? The hook.Add functions only get called once per hook so it doesn't matter if they are a tiny bit slower than garry's. Also something must be wrong with your gmod, because these are my test results

```
nr of iterations:	1000000
pairs:	0.049
for	0.007
ipairs:	0.062
```
for loops are nearly 10 times faster

I don't have much else to add to this discussion so I'll stop now.

**Comment by meepdarknessmeep** [comment]
@Nayruden I readded the bounds checking.

**Comment by c1yd3i** [comment]
here's a solution don't use such a shitty admin mod

**Comment by c1yd3i** [comment]
ulx is autistic

**Comment by Nayruden** [comment]
For everyone else's benefit: This pull request was locked due to additional trolling from another user, who wasn't part of the original conversation. We (Team Ulysses) are always open to serious discussion, but ad hominem wastes everyone's time.

**Pull request closed without merging**
