### PR TITLE
Make hooks better

### PR DESCRIPTION
**Pull request by meepdarknessmeep**
Changed how hooks are handled internally so it's better & faster

### CODE REVIEW

**Comment by comedinha** [comment]
Not work, my server down after 2 minutes...

**Comment by Divran** [comment]
I made a hook library too long ago, and this looks pretty similar to that with the lookup tables and such. Looks good.

**Comment by meepdarknessmeep** [comment]
It's how I code;

**Comment by zeaga** [comment]
It's probably just force of habit, jacky.  He may have learned Javascript before learning Lua.

I put a whitespace in functions without arguments.  Are they really needed?  No, not really.  It's just how I learned to write code.

**Comment by meepdarknessmeep** [comment]
There's a bug in this code, don't test/update it to the master branch yet - i am fixing it.

**Comment by meepdarknessmeep** [comment]
Updated to make it faster and fix a bug.

**Comment by MuteTM** [comment]
1) Can ULib function with the default Garry's Mod hook system?

2) Since ULib is already able to be modular, would it be a travesty to move the commands (and if possible, the hook system) to the modular system so that the user can easily choose what they do and don't want (a la Evolve)?

**Comment by meepdarknessmeep** [comment]
@MuteTM, this hook system is actually faster than default garry's mod's hook system.

**Comment by iSnipeu** [comment]
> @MuteTM, this hook system is actually faster than default garry's mod's hook system.

Maybe it could be implemented in the base then? If it's faster and adds priority functionality then I don't see why it can't be, and ulx won't need to override the hook library anymore.

**Comment by darkjacky** [comment]
ok, I have taken the time to test this. I replaced the default hook file and began optimizing.

I would like to know if you can get the same results as me.

my results:
default
0.00046752486834123 -- 3x 40 hooks
0.0015775307197217 -- 10x 40 hooks
2.247460795787 -- 100000x 10x 40 hooks

your edit
0.00047776477472183 -- 3x 40 hooks
0.001515798712699 -- 10x 40 hooks
2.1842334698654 -- 100000x 10x 40 hooks

my edit
0.00046986541838123 -- 3x 40 hooks
0.0015535400819431 -- 10x 40 hooks
1.7641328262142	-- 100000x 10x 40 hooks

my version: http://www.pastebin.ca/2906313 (< this would be a default hook replace file. for ulx add back the oldhooks and the loop.)

**Comment by Divran** [comment]
Nice work, but

>--this is faster than math.min and math.max
>--saves you 60 nanoseconds

this is unecessary in the hook.Add function. You're not going to be running this function a thousand times per tick. Most often, only one time per hook.

**Comment by darkjacky** [comment]
all of the tests are running hook.Run("hook")
the hook hook had 40 hooks from -20 to 20 and all returned nothing
and the x says how much times the 40 hooks i called in the once function.
then the last function was calling it 100000 times instead of just once

**Comment by Divran** [comment]
I see. Interesting

**Comment by darkjacky** [comment]
EDIT: Your version has a problem: it doesn't properly handle entity names. See https://github.com/Nayruden/Ulysses/blob/master/ulib/lua/ulib/shared/hook.lua#L186

yep thats right. however I only optimized meepdarknessmeep's version. and since he does not have that.

also the code you supplied didn't work out of the box after some editing it worked. but glitched a couple of things. so if you can fix it and repost your code that would be perfect.

**Comment by Divran** [comment]
Sure, if you can tell me how it didn't work, because it worked for me (except for hook.Remove, I'm aware that one doesn't work).

**Comment by darkjacky** [comment]
well it seems like you did last minute changes when you uploaded the file.
"local hook = hooks[i]" and then later in the function
"a,b,c,d,e,f = hook.fn( v.name, ... )" v is not defined.
I also had a problem with Clamp since that does not exist when you replace the default file somehow.
just reupload what you currently have. we can figure out something on the remove script.
apart from all this. the speed the module has... is like nothing i have seen so far real good. +1

I also made a couple of changes to the ULX hook script and with 2 small changes you can get the time down from the 100+ seconds to 2.3 seconds. So i'd recommend implementing those changes without much thought.
^ the changes made was: remove the resort table. and instead of adding the broken hook to the resort table call the sortHooks( name ) directly.
there are more optimizable things moving the gm thing to the bottom. or even removing it. 
and making those a,b,c,d,e,f variables local makes a tiny difference. but since its being called a 100 times a second even a small change can make a huge impact.

**Comment by Divran** [comment]
Ah yes, you're right about the 'v' thing. That's exactly what I did.

Making the a,b,c variables any more local than they already are in my script is not possible.

**Comment by darkjacky** [comment]
doing so is fine :) it will cost you another 40 bytes of storage but it will increase the speed of the code. and since we are talking about the speed of the code i'd do it.

**Comment by Divran** [comment]
I found out why mine was so blazing fast, lol. It was due to a mistake in the code. I didn't realize ULX's version called ´hook.Remove` inside the `hook.Add` function, and my `hook.Remove` was broken, so it was removing the wrong hooks during adding. Now I just need to figure out how to get the speed down to the same as yours.

**Comment by darkjacky** [comment]
http://pastebin.com/a4WAiseq

I changed some things. (I removed most of the comments since that makes it easier for me to read.)
The code made by Divran is clearly faster than anything so far.

"local priority = priority or 0" instead of "priority = Clamp(floor(priority or 0),-20,20)"
it does not really have to be clamped or rounded. and also it does not have to between -20 and 20.

"hook.priority > -20 and hook.priority < 20" instead of "hook.priority ~= -20 and hook.priority ~= 20" since it then allows that :)

"elseif IsValid( hook.name )" instead of "else if IsValid( hook.name )" I don't know why this is not this way in the default.

Removed the getting of the gm function from the hook.Call. since you are not supposed to use it that way. Garry's default does not have it either.

cleaned a couple of unused things.

**Comment by YourStalker** [comment]
Will we see this being merged any time soon? This seems useful as hell! (Going to try it out in a bit)

**Comment by Nayruden** [comment]
No; See https://github.com/Nayruden/Ulysses/tree/hook-update.

**Pull request closed without merging**
